package ProjFrames;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Services.DBconn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class Admin_dash extends javax.swing.JFrame {

    /**
     * Creates new form Admin_dash
     */
    CardLayout card;
    String userid;
    Connection conn;
    public Admin_dash(String userid) {
        initComponents();
        this.userid=userid;
        jLabel1.setText("Welcome " +  userid);
        card=(CardLayout) mainpanel.getLayout();
        try {
            conn = (new DBconn()).getDBconnection();
        } catch (Exception ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Mail = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        uslist = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        grlab = new javax.swing.JLabel();
        grpcb = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        Accall = new javax.swing.JButton();
        denall = new javax.swing.JButton();
        p5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ustable = new javax.swing.JTable();
        p4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        elelist = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        organiz = new javax.swing.JLabel();
        elename = new javax.swing.JLabel();
        sttime = new javax.swing.JLabel();
        durlab = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        orgname = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        p6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        elorgtable = new javax.swing.JTable();
        p7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        electable = new javax.swing.JTable();
        p8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        feedta = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainpanel.setBackground(new java.awt.Color(0, 255, 204));
        mainpanel.setLayout(new java.awt.CardLayout());

        p1.setBackground(new java.awt.Color(204, 204, 255));
        p1.setPreferredSize(new java.awt.Dimension(501, 300));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        mainpanel.add(p1, "card3");

        p2.setBackground(new java.awt.Color(204, 204, 255));
        p2.setName("p2"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Requests");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("E-mail:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setText("Mobile number:");

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ACCEPT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DENY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        uslist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        uslist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                uslistValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(uslist);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setText("Groupid:");

        grpcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All groups", "Computer", "Mechanical", "Electrical", "Electronics", "IT", "IC", "Chemical", "Civil", "Other group" }));
        grpcb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                grpcbItemStateChanged(evt);
            }
        });

        jLabel18.setText("Select By Group:");

        Accall.setBackground(new java.awt.Color(0, 51, 204));
        Accall.setForeground(new java.awt.Color(255, 255, 255));
        Accall.setText("Accept All");
        Accall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccallActionPerformed(evt);
            }
        });

        denall.setBackground(new java.awt.Color(0, 51, 204));
        denall.setForeground(new java.awt.Color(255, 255, 255));
        denall.setText("Deny All");
        denall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(p2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(p2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(p2Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(grlab, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(Accall))
                                .addGap(40, 40, 40)
                                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(denall))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(grpcb, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grpcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grlab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Accall)
                    .addComponent(denall))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        mainpanel.add(p2, "p2card");

        p5.setBackground(new java.awt.Color(204, 204, 255));
        p5.setPreferredSize(new java.awt.Dimension(467, 200));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("USER DETAILS");

        ustable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name", "E-Mail", "Mail", "Mobile number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(ustable);

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
        );

        mainpanel.add(p5, "p5card");

        p4.setBackground(new java.awt.Color(204, 204, 255));

        elelist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        elelist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                elelistValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(elelist);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ELECTION  REQUESTS");

        jLabel12.setText("Organizer-ID");

        jLabel13.setText("Name of Election");

        jLabel14.setText("Start Time");

        jLabel15.setText("Duration");

        jButton5.setBackground(new java.awt.Color(0, 0, 204));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("ACCEPT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 204));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("DENY");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4Layout.createSequentialGroup()
                        .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p4Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(elename, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(organiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sttime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(durlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(p4Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jButton5)
                                .addGap(66, 66, 66)
                                .addComponent(jButton6)))
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(organiz, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elename, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sttime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durlab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(69, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );

        mainpanel.add(p4, "p4card");

        p3.setBackground(new java.awt.Color(204, 204, 255));

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Election Organizers Requests");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("NAME OF THE ORGANIZATION");

        orgname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orgname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ACCEPT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 204));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("DENY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p3Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orgname, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(0, 54, Short.MAX_VALUE))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton3)
                        .addGap(93, 93, 93)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orgname, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        mainpanel.add(p3, "p3card");

        p6.setBackground(new java.awt.Color(204, 204, 255));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ELECTION ORGANIZER DETAILS");

        elorgtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(elorgtable);

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainpanel.add(p6, "p6card");

        p7.setBackground(new java.awt.Color(204, 204, 255));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ELECTION DETAILS");

        electable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Election ID", "Organizer", "Name", "Start Time", "Duration", "Status", "Winner ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(electable);

        javax.swing.GroupLayout p7Layout = new javax.swing.GroupLayout(p7);
        p7.setLayout(p7Layout);
        p7Layout.setHorizontalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );
        p7Layout.setVerticalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p7Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
        );

        mainpanel.add(p7, "p7card");

        p8.setBackground(new java.awt.Color(204, 204, 255));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("FEEDBACK");

        feedta.setColumns(20);
        feedta.setRows(5);
        jScrollPane7.setViewportView(feedta);

        javax.swing.GroupLayout p8Layout = new javax.swing.GroupLayout(p8);
        p8.setLayout(p8Layout);
        p8Layout.setHorizontalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        p8Layout.setVerticalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p8Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );

        mainpanel.add(p8, "p8card");

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 102));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 4));

        jMenu1.setBackground(new java.awt.Color(102, 255, 102));
        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jMenu1.setText("Approvals     ");

        jMenuItem1.setText("User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Elections");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Election Organizers");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(102, 255, 102));
        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jMenu2.setText("Details    ");

        jMenuItem5.setText("Election Organizer Details");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setText("User Details");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Election Records");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(102, 255, 102));
        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jMenu3.setText("Registrations   ");

        jMenuItem7.setText("User Registration");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem10.setText("Election Organizer");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(102, 255, 102));
        jMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jMenu4.setText("Other");

        jMenuItem8.setText("View Feedback");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Change Password");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem11.setText("Logout");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        card.show(mainpanel,"p2card");
        String str= "SELECT userid FROM userapp WHERE status='p'";
        DefaultListModel dlm = new DefaultListModel();
        Statement stat=null;
        try {
            stat = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ResultSet rs = stat.executeQuery(str);
            while(rs.next()){
               dlm.addElement(rs.getString(1));
            }
            uslist.setModel(dlm);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String usid=uslist.getSelectedValue();
        if(usid==null){
           JOptionPane.showMessageDialog(this,"No userid selected");
        }
        else{
           String str="SELECT * FROM userapp WHERE userid='" + usid + "'";
           String passw="",usname="",usmail="",usmob="",grid="";
        try {
            Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(str);
            while(rs.next()){
              passw=rs.getString(2);  
              usname=rs.getString(3);
              usmail=rs.getString(4);
              usmob=rs.getString(5);
              grid=rs.getString(6);
            }
          String ins="INSERT into users VALUES(\"" + usid + "\", \"" + passw + "\", \"" + usname + "\", \"" + usmail + "\", \"" + grid + "\", \"" + usmob + "\")";
          String del="DELETE FROM userapp WHERE userid=\"" + usid + "\"";
          stat.executeUpdate(ins);
          stat.executeUpdate(del);
          DefaultListModel dlm=(DefaultListModel) uslist.getModel();
          dlm.removeElement(usid);
          uslist.setModel(dlm);
              Name.setText("");
              Mail.setText("");
              mobile.setText("");
              grlab.setText("");
        }
         catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"No user selected");
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void uslistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_uslistValueChanged
        // TODO add your handling code here:
        String usid=uslist.getSelectedValue();
        String str="SELECT * FROM userapp WHERE userid='" + usid + "'";
        try {
            Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(str);
            while(rs.next()){
              String usname=rs.getString(3);
              String usmail=rs.getString(4);
              String usmob=rs.getString(5);
              String grid=rs.getString(6);
              Name.setText(usname);
              Mail.setText(usmail);
              mobile.setText(usmob);
              grlab.setText(grid);
            }
        } catch (SQLException ex) {
         
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_uslistValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          String usid=uslist.getSelectedValue();
        if(usid==null){
           JOptionPane.showMessageDialog(this,"No userid selected");
        }
        else{
         try{
          Statement stat=conn.createStatement();
          String del="DELETE FROM userapp WHERE userid=\"" + usid + "\"";
          stat.executeUpdate(del);
          DefaultListModel dlm=(DefaultListModel) uslist.getModel();
          dlm.removeElement(usid);
          uslist.setModel(dlm);
              Name.setText("");
              Mail.setText("");
              mobile.setText("");
              grlab.setText("");
        }
         catch (SQLException ex) {
             JOptionPane.showMessageDialog(this,"No userid selected");
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        card.show(mainpanel, "p4card");
        String str= "SELECT electionid FROM electionsapp WHERE status='p'";
        DefaultListModel dlm=new DefaultListModel();
        Statement stat=null;
        try {
            stat = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ResultSet rs = stat.executeQuery(str);
            while(rs.next()){
               dlm.addElement(rs.getString(1));
            }
            elelist.setModel(dlm);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        card.show(mainpanel, "p3card");
        String str= "SELECT userid FROM orgapp WHERE status='p'";
        DefaultListModel dlm=new DefaultListModel();
        Statement stat=null;
        try {
            stat = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ResultSet rs = stat.executeQuery(str);
            while(rs.next()){
               dlm.addElement(rs.getString(1));
            }
            jList1.setModel(dlm);
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        String orgid=jList1.getSelectedValue();
        String str="SELECT * FROM orgapp WHERE userid='" + orgid + "'";
        try {
            Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(str);
            String oname="";
            while(rs.next()){
              oname=rs.getString(3);

               
            }
            orgname.setText(oname);
        } catch (SQLException ex) {
         
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String orgid=jList1.getSelectedValue();
        if(orgid==null){
           JOptionPane.showMessageDialog(this,"No userid selected");
        }
        else{
           String str="SELECT * FROM orgapp WHERE userid='" + orgid + "'";
           String passw="",oname="";
        try {
            Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(str);
            while(rs.next()){
              passw=rs.getString(2);  
              oname=rs.getString(3);
              
            }
          String ins="INSERT into organizacc VALUES(\"" + orgid + "\", \"" + passw + "\", \"" + oname + "\", \"organizer\")";
          String del="DELETE FROM orgapp WHERE userid=\"" + orgid + "\"";
          stat.executeUpdate(ins);
          stat.executeUpdate(del);
          DefaultListModel dlm=(DefaultListModel) jList1.getModel();
          dlm.removeElement(orgid);
          jList1.setModel(dlm);
          orgname.setText("");
        }
         catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"No user selected");
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String orgid=jList1.getSelectedValue();
        if(orgid==null){
           JOptionPane.showMessageDialog(this,"No userid selected");
        }
        else{
         try{
          Statement stat=conn.createStatement();
          String del="DELETE FROM orgapp WHERE userid=\"" + orgid + "\"";
          stat.executeUpdate(del);
          DefaultListModel dlm=(DefaultListModel) jList1.getModel();
          dlm.removeElement(orgid);
          jList1.setModel(dlm);
          orgname.setText("");
        }
         catch (SQLException ex) {
             JOptionPane.showMessageDialog(this,"No userid selected");
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void elelistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_elelistValueChanged
        // TODO add your handling code here:
        String elecid=elelist.getSelectedValue();
        String str="SELECT * FROM electionsapp WHERE electionid=\"" + elecid + "\"";
        try {
            Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(str);
            String elecname="",org="",start="",dur="";
            while(rs.next()){
              elecname=rs.getString(2);
              org=rs.getString(3);
              start=rs.getString(4);
              dur=rs.getString(5);
            }
            elename.setText(elecname);
            organiz.setText(org);
            sttime.setText(start);
            durlab.setText(dur);
        } catch (SQLException ex) {
         
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_elelistValueChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String elecid=elelist.getSelectedValue();
        if(elecid==null){
           JOptionPane.showMessageDialog(this,"No Election selected");
        }
        else{
           String str="SELECT * FROM electionsapp WHERE electionid='" + elecid + "'";
           String elecname="",oname="",start="",dur="";
        try {
            Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(str);
            while(rs.next()){
              elecname=rs.getString(2);  
              oname=rs.getString(3);
              start=rs.getString(4);
              dur=rs.getString(5);
            }
            System.out.println(start);
          String ins="INSERT into elections VALUES(\"" + elecid + "\", \"" + oname + "\", \"" + elecname + "\", \"" + start + "\", \"" + dur + "\", 'b', \"null\")";
          String del="DELETE FROM electionsapp WHERE electionid=\"" + elecid + "\"";
          stat.executeUpdate(ins);
          stat.executeUpdate(del);
          DateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
          
          java.util.Date dt = null;
        try {
            dt = dateformat.parse(start);
        } catch (ParseException ex) {
            Logger.getLogger(Org_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(dt);
        Timestamp stts=new Timestamp(dt.getTime());
        System.out.println(stts);
        String part= "start" + elecid;
        String strst="CREATE EVENT " + part + " ON SCHEDULE AT ? DO UPDATE elections SET election_stat='r' WHERE electionid='" + elecid + "';";
            PreparedStatement ps2 = conn.prepareStatement(strst); 
            ps2.setTimestamp(1, stts);
            ps2.executeUpdate();
        Calendar cal= Calendar.getInstance();
        Date d= new Date(stts.getTime());
        cal.setTime(d);
        cal.add(Calendar.MINUTE, Integer.parseInt(dur));
        d=cal.getTime();
        long l=d.getTime();
        stts.setTime(l);
        System.out.println(stts);
        part="end"+elecid;
        String endst="CREATE EVENT " + part + " ON SCHEDULE AT ? DO UPDATE elections SET election_stat='u' WHERE electionid='" + elecid + "';";
        PreparedStatement ps3 = conn.prepareStatement(endst); 
        ps3.setTimestamp(1, stts);
        ps3.executeUpdate();
          DefaultListModel dlm=(DefaultListModel) elelist.getModel();
          dlm.removeElement(elecid);
          elelist.setModel(dlm);
          elename.setText("");
          organiz.setText("");
          sttime.setText("");
          durlab.setText("");
        }
         catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(this,"No election selected");
        }
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String elecid=elelist.getSelectedValue();
        if(elecid==null){
           JOptionPane.showMessageDialog(this,"No Election selected");
        }
        else{
        try{
            Statement stat=conn.createStatement();
          String del="DELETE FROM electionsapp WHERE electionid=\"" + elecid + "\"";
          stat.executeUpdate(del);
          DefaultListModel dlm=(DefaultListModel) elelist.getModel();
          dlm.removeElement(elecid);
          elelist.setModel(dlm);
          elename.setText("");
          organiz.setText("");
          sttime.setText("");
          durlab.setText("");
        }
        catch (SQLException ex) {
                
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(this,"No election selected");
        }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            // TODO add your handling code here:
            card.show(mainpanel,"p5card");
            Statement stat= conn.createStatement();
            String quer="SELECT * FROM users";
            ResultSet rs= stat.executeQuery(quer);
            DefaultTableModel tab= (DefaultTableModel) ustable.getModel();
            tab.setRowCount(0);
            String col1="",col2="",col3="",col4="",col5="";
            while(rs.next()){
              col1=rs.getString(1);
              col2=rs.getString(3);
              col3=rs.getString(4);
              col4=rs.getString(5);
              col5=rs.getString(6);
              tab.addRow(new String[]{col1,col2,col3,col4,col5});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        try{
            card.show(mainpanel,"p6card");
            Statement stat= conn.createStatement();
            String quer="SELECT * FROM organizacc WHERE designation='organizer'";
            ResultSet rs= stat.executeQuery(quer);
            DefaultTableModel tab= (DefaultTableModel) elorgtable.getModel();
            tab.setRowCount(0);
            String col1="",col2="";
            while(rs.next()){
              col1=rs.getString(1);
              col2=rs.getString(3);
              tab.addRow(new String[]{col1,col2});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
                try{
            card.show(mainpanel,"p7card");
            Statement stat= conn.createStatement();
            String quer="SELECT * FROM elections";
            ResultSet rs= stat.executeQuery(quer);
            DefaultTableModel tab= (DefaultTableModel) electable.getModel();
            tab.setRowCount(0);
            while(rs.next()){
              String col1=rs.getString(1);
              String col2=rs.getString(2);
              String col3=rs.getString(3);
              String col4=rs.getString(4);
              String col5=rs.getString(5);
              String col7=rs.getString(7);
              String status=rs.getString(6);
              String col6="";
              if(status.equals("b")){
                col6="Upcoming";
              }
              else if(status.equals("r")){
                col6="Ongoing";
              }
              else if(status.equals("u")){
                col6="Result unpublished";
              }
              else{
                col6="Completed";
              }
              tab.addRow(new String[]{col1,col2,col3,col4,col5,col6,col7});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new UserReg("admin").setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new Loginscr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            // TODO add your handling code here:
            card.show(mainpanel,"p8card");
            feedta.append("----------------------FEEDBACK------------------");
            String str="SELECT * FROM feedback ORDER BY time ASC";
            Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(str);
            while(rs.next()){
                String usid=rs.getString(1);
                String desig=rs.getString(2);
                String time=rs.getString(3);
                String msg=rs.getString(4);
           
              
              feedta.append("\n\n\nFROM: " + usid + "       DESIGNATION: " + desig + "      AT " + time + "\n" + msg + "\n----------------------------");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new RegistrationForm("admin").setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new Chpass(userid,"organizer").setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void grpcbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_grpcbItemStateChanged
        // TODO add your handling code here:
        String str="";
        String group=(String) grpcb.getSelectedItem();
        if(group.equals("All groups")){
          str= "SELECT userid FROM userapp WHERE status='p'";
        }
        else{
          str= "SELECT userid FROM userapp WHERE status='p' AND groupid='" + group + "'";
        }
        DefaultListModel dlm = new DefaultListModel();
        Statement stat=null;
        try {
            stat = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ResultSet rs = stat.executeQuery(str);
            while(rs.next()){
               dlm.addElement(rs.getString(1));
            }
            uslist.setModel(dlm);
             Name.setText("");
              Mail.setText("");
              mobile.setText("");
              grlab.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_grpcbItemStateChanged

    private void AccallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccallActionPerformed
        // TODO add your handling code here:
           DefaultListModel dlm= (DefaultListModel) uslist.getModel();
           int nuser=dlm.getSize();
        for(int i=0;i<nuser;i++){
           String usid=(String) dlm.elementAt(i);
           String str="SELECT * FROM userapp WHERE userid='" + usid + "'";
           String passw="",usname="",usmail="",usmob="",grid="";
        try {
            Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(str);
            while(rs.next()){
              passw=rs.getString(2);  
              usname=rs.getString(3);
              usmail=rs.getString(4);
              usmob=rs.getString(5);
              grid=rs.getString(6);
            }
          String ins="INSERT into users VALUES(\"" + usid + "\", \"" + passw + "\", \"" + usname + "\", \"" + usmail + "\", \"" + grid + "\", \"" + usmob + "\")";
          String del="DELETE FROM userapp WHERE userid=\"" + usid + "\"";
          stat.executeUpdate(ins);
          stat.executeUpdate(del);
              Name.setText("");
              Mail.setText("");
              mobile.setText("");
              grlab.setText("");
        }
         catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"No user selected");
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        dlm.removeAllElements();
        uslist.setModel(dlm);
    }//GEN-LAST:event_AccallActionPerformed

    private void denallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denallActionPerformed
        // TODO add your handling code here:
         DefaultListModel dlm= (DefaultListModel) uslist.getModel();
         int nuser=dlm.getSize();
         for(int i=0;i<nuser;i++){
           String usid=(String) dlm.elementAt(i);
         try{
          Statement stat=conn.createStatement();
          String del="DELETE FROM userapp WHERE userid=\"" + usid + "\"";
          stat.executeUpdate(del);
              Name.setText("");
              Mail.setText("");
              mobile.setText("");
              grlab.setText("");
        }
         catch (SQLException ex) {
             JOptionPane.showMessageDialog(this,"No userid selected");
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
         dlm.removeAllElements();
         uslist.setModel(dlm);
    }//GEN-LAST:event_denallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accall;
    private javax.swing.JLabel Mail;
    private javax.swing.JLabel Name;
    private javax.swing.JButton denall;
    private javax.swing.JLabel durlab;
    private javax.swing.JTable electable;
    private javax.swing.JList<String> elelist;
    private javax.swing.JLabel elename;
    private javax.swing.JTable elorgtable;
    private javax.swing.JTextArea feedta;
    private javax.swing.JLabel grlab;
    private javax.swing.JComboBox<String> grpcb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel organiz;
    private javax.swing.JLabel orgname;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JPanel p8;
    private javax.swing.JLabel sttime;
    private javax.swing.JList<String> uslist;
    private javax.swing.JTable ustable;
    // End of variables declaration//GEN-END:variables
}
