package ProjFrames;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BoxLayout;

import Services.DBconn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class Loginscr extends javax.swing.JFrame {

    /**
     * Creates new form Loginscr
     */
    Connection conn;
    
    public Loginscr() {
        initComponents();
            try {
                
            	conn = (new DBconn()).getDBconnection();
          
            } catch (Exception ex) {
                System.out.println("Connecting  problem");
                Logger.getLogger(Loginscr.class.getName()).log(Level.SEVERE, null, ex);
            }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Backb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setResizable(false);
        getContentPane().setLayout(new BoxLayout(getContentPane(),BoxLayout.Y_AXIS));
        javax.swing.JPanel pnl = new javax.swing.JPanel();
        pnl.setPreferredSize(new Dimension(600,50));
        getContentPane().add(pnl);
        
        Backb.setBackground(new java.awt.Color(0, 51, 204));
        Backb.setForeground(new java.awt.Color(255, 255, 255));
        Backb.setSize(new java.awt.Dimension(4, 10));
        Backb.setText("BACK");
        Backb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(Backb,BorderLayout.WEST);
        jPanel1.add(jLabel2,BorderLayout.CENTER);
        getContentPane().add(jPanel1);
        
        jPanel2.setLayout(new GridLayout(4,1));
        
        jPanel21.setLayout(new FlowLayout());
        jPanel22.setLayout(new FlowLayout());
        
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User ID:");
        jTextField1.setPreferredSize(new Dimension(112,28));
        jPanel21.add(jLabel3);
        jPanel21.add(jTextField1);
        
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password:");
        jPanel22.add(jLabel4);
        jPanel22.add(jPasswordField1);
        jPasswordField1.setPreferredSize(new Dimension(112,28));
        jPanel2.add(new javax.swing.JPanel());
        jPanel2.add(jPanel21);
        jPanel2.add(jPanel22);
        
        getContentPane().add(jPanel2);
        
        jPanel3.setLayout(new FlowLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("Login as:");
        jPanel3.add(jLabel5);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Election Organizer", "User" }));

        jPanel3.add(jComboBox1);

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        


        getContentPane().add(jLabel6);
        getContentPane().add(jPanel3);
        getContentPane().add(jButton1);
        getContentPane().add(new javax.swing.JPanel());
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Statement stat = null;
        try {
            stat = (Statement) conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Loginscr.class.getName()).log(Level.SEVERE, null, ex);
        }
         String usertype =  (String) jComboBox1.getSelectedItem();
         String str="";
         String usid=jTextField1.getText();
         String passw=jPasswordField1.getText();
         boolean b=false;
         boolean b2=false;
         if(usertype.equals("Administrator")){
           str="SELECT userid, password FROM organizacc WHERE userid='" + usid + "' AND designation='admin'";
         }
         else if(usertype.equals("Election Organizer")){
            str="SELECT userid, password FROM organizacc WHERE userid='" + usid + "' AND designation='organizer'";
         }
         else{
            str="SELECT userid, password FROM users WHERE userid='" + usid + "'";
         }
        try {
            ResultSet rs = stat.executeQuery(str);
            while(rs.next()){
               System.out.println(rs.getString(1));
               b=true;
               if(rs.getString(2).equals(passw)){
                 b2=true;
                 break;
               }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Loginscr.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(b2){
            jLabel6.setText("Entered");
            if(usertype=="Administrator")
                new Admin_dash(usid).setVisible(true);
            else if(usertype=="Election Organizer")
                new Org_dash(usid).setVisible(true);
            else
                new User_dash(usid).setVisible(true);
           this.dispose();
        }
        else if(b)
            jLabel6.setText("Incorrect Password");
        else
            jLabel6.setText("No such user");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbActionPerformed
        // TODO add your handling code here:
        new homescr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginscr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginscr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginscr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginscr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new Loginscr().setVisible(true);
                   
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backb;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
