package ProjFrames;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BoxLayout;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

import Services.DBconn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class ResultFrame extends javax.swing.JFrame {

    /**
     * Creates new form ResultFrame
     */
    String elecid,status;
    Connection conn;
    public ResultFrame(String str1,String str2) {
        initComponents();
        elecid=str1;
        status=str2;
         DefaultTableModel tab= (DefaultTableModel) jTable1.getModel();
         tab.setRowCount(0);
         //jPanel2.removeAll();
         DefaultPieDataset pds = new DefaultPieDataset();
         
        try {
            conn=(new DBconn()).getDBconnection();
        } catch (Exception ex) {
            Logger.getLogger(ReqCheck.class.getName()).log(Level.SEVERE, null, ex);
        }
        chpanel.setText(elecid);
        if(status.equals("Result Unpublished")){
          jLabel4.setText("Winner Undeclared");
        }
        else{
          String q1="SELECT winnerid FROM elections WHERE electionid='" + elecid + "'";
            try {
                Statement st1=conn.createStatement();
                ResultSet rs1=st1.executeQuery(q1);
                while(rs1.next()){
                  jLabel4.setText(rs1.getString(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(ResultFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            String q2="SELECT cand_id,votes FROM elecvotes WHERE electionid='" + elecid + "'";
            try {
                Statement st2=conn.createStatement();
                ResultSet rs2=st2.executeQuery(q2);
                String col1="";
                int col2;
            while(rs2.next()){
              col1=rs2.getString(1);
              col2=rs2.getInt(2);
              tab.addRow(new String[]{col1,Integer.toString(col2)});
              pds.setValue(col1, new Integer(col2));
            }
            } catch (SQLException ex) {
                Logger.getLogger(ResultFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            JFreeChart chart= ChartFactory.createPieChart("Vote Distribution", pds,true,true,true);
            PiePlot p = (PiePlot) chart.getPlot();
            ChartPanel pc= new ChartPanel(chart);
            jPanel2.setLayout(new BorderLayout());
            jPanel2.add(pc,BorderLayout.CENTER);
            jPanel2.validate();
         // ChartFrame fr= new ChartFrame("Pie",chart);
          //fr.setVisible(true);
          //fr.setSize(450,500);
        }
        
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chpanel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 720));
        setResizable(false);
        getContentPane().setLayout(new BoxLayout(getContentPane(),BoxLayout.Y_AXIS));


        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Voting Result");
        
        getContentPane().add(jLabel1);
        
        javax.swing.JPanel jp11 = new javax.swing.JPanel();
        javax.swing.JPanel jp12 = new javax.swing.JPanel();
        
        jp11.setLayout(new FlowLayout());
        jLabel2.setText("ELECTION ID:");
        jp11.add(jLabel2);
        chpanel.setText("jLabel3");
        jp11.add(chpanel);
        jp12.setLayout(new FlowLayout());
        jLabel3.setText("Winner ID:");
        jp12.add(jLabel3);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jp12.add(jLabel4);
        getContentPane().add(jp11);
        getContentPane().add(jp12);


        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Votes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jPanel1.add(jScrollPane1);
        getContentPane().add(jPanel1);
        javax.swing.JPanel pnl = new javax.swing.JPanel();
        pnl.setPreferredSize(new Dimension(800,20));
        getContentPane().add(pnl);
        jPanel2.setLayout(new FlowLayout());
        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
