package ProjFrames;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import Services.DBconn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class setWinner extends javax.swing.JFrame {

    /**
     * Creates new form setWinner
     */
    String electionid;
    Connection conn;
    public setWinner(String str1) {
        initComponents();
        electionid=str1;
        ellabel.setText(electionid);
        try {
            conn=(new DBconn()).getDBconnection();
        } catch (Exception ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            int vot=0;
            String q1="SELECT MAX(votes) FROM elecvotes WHERE electionid='" + electionid + "'";
            Statement stat=conn.createStatement();
            ResultSet rs1=stat.executeQuery(q1);
            if(rs1.next()){
              vot=rs1.getInt(1);
            }
            String q2="SELECT cand_id FROM elecvotes WHERE electionid='" + electionid + "' AND votes=" + vot;
            ResultSet rs2=stat.executeQuery(q2);
            DefaultListModel dlm= new DefaultListModel();
            while(rs2.next()){
             dlm.addElement(rs2.getString(1));
            }
            jList1.setModel(dlm);
            } catch (SQLException ex) {
            Logger.getLogger(setWinner.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namlabel = new javax.swing.JLabel();
        maillabel = new javax.swing.JLabel();
        mnlabel = new javax.swing.JLabel();
        gridlabel = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ellabel = new javax.swing.JLabel();
        dwbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new Dimension(600,400));
        setResizable(false);
        getContentPane().setLayout(new BoxLayout(getContentPane(),BoxLayout.X_AXIS));

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setToolTipText("");
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.JPanel jpanel2 = new javax.swing.JPanel();
        jpanel2.setLayout(new BoxLayout(jpanel2,BoxLayout.Y_AXIS));


        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Winner ID List");
        jpanel2.add(jLabel1);
        jpanel2.add(jScrollPane1);
        getContentPane().add(jpanel2);
        
        jPanel1.setLayout(new BoxLayout(jPanel1,BoxLayout.Y_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SET WINNER");
        jPanel1.add(jLabel2);
        
        javax.swing.JPanel jp1 = new javax.swing.JPanel();
        jp1.setLayout(new FlowLayout());
        jLabel3.setText("Election ID:");
        jp1.add(jLabel3);
        jp1.add(ellabel);
        jPanel1.add(jp1);
        
        javax.swing.JPanel jp2 = new javax.swing.JPanel();
        jp2.setLayout(new FlowLayout());
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("NAME:");
        jp2.add(jLabel30);
        jp2.add(namlabel);
        jPanel1.add(jp2);
        
        javax.swing.JPanel jp3 = new javax.swing.JPanel();
        jp3.setLayout(new FlowLayout());
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("E-MAIL:");
        jp3.add(jLabel31); 
        jp3.add(maillabel);
        jPanel1.add(jp3);
        
        javax.swing.JPanel jp4 = new javax.swing.JPanel();
        jp4.setLayout(new FlowLayout());
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Mobile Number:");
        jp4.add(jLabel32);
        jp4.add(mnlabel);
        jPanel1.add(jp4);
        
        javax.swing.JPanel jp5 = new javax.swing.JPanel();
        jp5.setLayout(new FlowLayout());
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Group ID:");
        jp5.add(jLabel33);
        jp5.add(gridlabel);
        jPanel1.add(jp5);

        dwbutton.setBackground(new java.awt.Color(0, 51, 255));
        dwbutton.setForeground(new java.awt.Color(255, 255, 255));
        dwbutton.setText("DECLARE AS WINNER");
        dwbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dwbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(dwbutton);
        jPanel1.add(new javax.swing.JPanel());
        getContentPane().add(jPanel1);


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:
            String candid=jList1.getSelectedValue();
            String quer1="SELECT * FROM users WHERE userid='" + candid + "'";
            Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(quer1);
            while(rs.next()){
               namlabel.setText(rs.getString(3));
               maillabel.setText(rs.getString(4));
               mnlabel.setText(rs.getString(6));
               gridlabel.setText(rs.getString(5));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Org_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void dwbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dwbuttonActionPerformed
        // TODO add your handling code here:
        String winner=jList1.getSelectedValue();
        if(winner==null){
         JOptionPane.showMessageDialog(this,"No Winner Selected");
        }
        else{
            try {
                Statement stat=conn.createStatement();
                String up="UPDATE elections SET winnerid='" + winner + "', election_stat='c' WHERE electionid='" + electionid + "'";
                stat.executeUpdate(up);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(setWinner.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
    }//GEN-LAST:event_dwbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setWinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setWinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setWinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setWinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dwbutton;
    private javax.swing.JLabel ellabel;
    private javax.swing.JLabel gridlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maillabel;
    private javax.swing.JLabel mnlabel;
    private javax.swing.JLabel namlabel;
    // End of variables declaration//GEN-END:variables
}
