package ProjFrames;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import Services.DBconn;
import Services.SendEmail;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class User_dash extends javax.swing.JFrame {

    /**
     * Creates new form User_dash
     */
    String userid;
    Connection conn;
    CardLayout card;
    FileInputStream fin=null;
    public User_dash(String userid) {
        initComponents();
        this.userid=userid;
        jLabel1.setText("Welcome " + userid);
                card=(CardLayout) mainpanel.getLayout();
        try {
            conn=(new DBconn()).getDBconnection();
        } catch (Exception ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        mainpanel = new javax.swing.JPanel();
        pan1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pan2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        usertab = new javax.swing.JTable();
        pan3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        orgtab = new javax.swing.JTable();
        pan4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        electab = new javax.swing.JTable();
        pan5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        votereleclist = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stlabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        durlabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        statlabel = new javax.swing.JLabel();
        prvotbutton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        pan6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        celeclist = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainpanel.setLayout(new java.awt.CardLayout());

        pan1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        mainpanel.add(pan1, "card2");

        pan2.setBackground(new java.awt.Color(204, 204, 255));
        pan2.setPreferredSize(new java.awt.Dimension(467, 200));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("USER DETAILS");

        usertab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name", "E-Mail", "Mail", "Mobile number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(usertab);

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainpanel.add(pan2, "pan2card");

        pan3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ELECTION ORGANIZER DETAILS");

        orgtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(orgtab);

        javax.swing.GroupLayout pan3Layout = new javax.swing.GroupLayout(pan3);
        pan3.setLayout(pan3Layout);
        pan3Layout.setHorizontalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        pan3Layout.setVerticalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        mainpanel.add(pan3, "pan3card");

        pan4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ELECTION DETAILS");

        electab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Election ID", "Organizer", "Name", "Start Time", "Duration", "Status", "Winner ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(electab);

        javax.swing.GroupLayout pan4Layout = new javax.swing.GroupLayout(pan4);
        pan4.setLayout(pan4Layout);
        pan4Layout.setHorizontalGroup(
            pan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        pan4Layout.setVerticalGroup(
            pan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainpanel.add(pan4, "pan4card");

        pan5.setBackground(new java.awt.Color(153, 153, 255));

        votereleclist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        votereleclist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                votereleclistValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(votereleclist);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VOTE FOR ELECTION");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Name:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Start Time:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Duration (in min):");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Status:");

        prvotbutton.setBackground(new java.awt.Color(51, 51, 255));
        prvotbutton.setForeground(new java.awt.Color(255, 255, 255));
        prvotbutton.setText("Proceed Voting");
        prvotbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prvotbuttonActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("View Candidates");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("View Result");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan5Layout = new javax.swing.GroupLayout(pan5);
        pan5.setLayout(pan5Layout);
        pan5Layout.setHorizontalGroup(
            pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pan5Layout.createSequentialGroup()
                                .addGap(0, 88, Short.MAX_VALUE)
                                .addComponent(jButton5)
                                .addGap(48, 48, 48)
                                .addComponent(prvotbutton)
                                .addGap(30, 30, 30)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(32, Short.MAX_VALUE))))
                    .addGroup(pan5Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan5Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan5Layout.createSequentialGroup()
                                .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)))
                        .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pan5Layout.setVerticalGroup(
            pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pan5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prvotbutton)
                        .addComponent(jButton5))
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainpanel.add(pan5, "pan5");

        pan6.setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setText("Send Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        celeclist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        celeclist.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                celeclistValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(celeclist);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Election ID");

        jLabel6.setText("Organizer:");

        jLabel8.setText("Name:");

        jLabel12.setText("Start Time:");

        jLabel13.setText("Duration (min):");

        jTextField2.setEditable(false);

        jTextField3.setEditable(false);

        jTextField4.setEditable(false);

        jTextField5.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SEND CANDIDATE REQUEST");

        jButton2.setText("Choose Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel17.setText("Enter a message:");

        jLabel18.setText("Candidate Image");

        jButton3.setText("Remove Image");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan6Layout = new javax.swing.GroupLayout(pan6);
        pan6.setLayout(pan6Layout);
        pan6Layout.setHorizontalGroup(
            pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan6Layout.createSequentialGroup()
                        .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pan6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pan6Layout.createSequentialGroup()
                                .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan6Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)))
                                .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(39, 39, 39)
                        .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pan6Layout.setVerticalGroup(
            pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan6Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(pan6Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pan6Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pan6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pan6Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(pan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        mainpanel.add(pan6, "pan6");

        jMenu1.setText("Details     ");

        jMenuItem1.setText("User Details");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Election Organizer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Election Records");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Elections    ");

        jMenuItem4.setText("Election Operations");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Candidate Request");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Other       ");

        jMenuItem7.setText("Provide Feedback");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Change Password");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Logout");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("Delete Account");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try{
             card.show(mainpanel,"pan4card");
            Statement stat= conn.createStatement();
            String quer="SELECT * FROM elections";
            ResultSet rs= stat.executeQuery(quer);
            DefaultTableModel tab= (DefaultTableModel) electab.getModel();
            tab.setRowCount(0);
            while(rs.next()){
               System.out.println("Inside");
              String col1=rs.getString(1);
              String col2=rs.getString(2);
              String col3=rs.getString(3);
              String col4=rs.getString(4);
              String col5=rs.getString(5);
              String col7=rs.getString(7);
              String status=rs.getString(6);
              String col6="";
              if(status.equals("b")){
                col6="Upcoming";
              }
              else if(status.equals("r")){
                col6="Ongoing";
              }
              else if(status.equals("u")){
                col6="Result unpublished";
              }
              else{
                col6="Completed";
              }
              tab.addRow(new String[]{col1,col2,col3,col4,col5,col6,col7});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new Feedback(userid,"user").setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
           try{
            card.show(mainpanel,"pan2card");
            Statement stat= conn.createStatement();
            String quer="SELECT * FROM users";
            ResultSet rs= stat.executeQuery(quer);
            DefaultTableModel tab= (DefaultTableModel) usertab.getModel();
            tab.setRowCount(0);
            String col1="",col2="",col3="",col4="",col5="";
            while(rs.next()){
              col1=rs.getString(1);
              col2=rs.getString(3);
              col3=rs.getString(4);
              col4=rs.getString(5);
              col5=rs.getString(6);
              tab.addRow(new String[]{col1,col2,col3,col4,col5});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         try{
            card.show(mainpanel,"pan3card");
            Statement stat= conn.createStatement();
            String quer="SELECT * FROM organizacc WHERE designation='organizer'";
            ResultSet rs= stat.executeQuery(quer);
            DefaultTableModel tab= (DefaultTableModel) orgtab.getModel();
            tab.setRowCount(0);
            String col1="",col2="";
            while(rs.next()){
              col1=rs.getString(1);
              col2=rs.getString(3);
              tab.addRow(new String[]{col1,col2});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new Chpass(userid,"user").setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new Loginscr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            // TODO add your handling code here:
            card.show(mainpanel, "pan5");
            String quer1= "SELECT voters.election_id FROM voters INNER JOIN elections on voters.election_id=elections.electionid WHERE voters.userid='" + userid + "'";
            Statement stat1=conn.createStatement();
            ResultSet rs1=stat1.executeQuery(quer1);
            DefaultListModel dlm=new DefaultListModel();
            while(rs1.next()){
                dlm.addElement(rs1.getString(1));
            }
            votereleclist.setModel(dlm);
        } catch (SQLException ex) {
            Logger.getLogger(User_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void votereleclistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_votereleclistValueChanged
        // TODO add your handling code here:
         String elecid=votereleclist.getSelectedValue();
        String str="SELECT * FROM elections WHERE electionid=\"" + elecid + "\"";
        try {
            Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(str);
            String elecname="",status="",start="",dur="";
            while(rs.next()){
              elecname=rs.getString(3);
              start=rs.getString(4);
              dur=rs.getString(5);
              status=rs.getString(6);
            }
            namelabel.setText(elecname);
            stlabel.setText(start);
            durlabel.setText(dur);
            if(status.equals("b")){
                statlabel.setText("Upcoming");
                prvotbutton.setEnabled(false);
                jButton5.setEnabled(false);
            }
            else if(status.equals("r")){
               statlabel.setText("Ongoing");
               prvotbutton.setEnabled(true);
               jButton5.setEnabled(false);
            }
            else if(status.equals("u")){
              statlabel.setText("Result Unpublished");
              prvotbutton.setEnabled(false);
              jButton5.setEnabled(false);
            }
            else{
              statlabel.setText("Completed");
              prvotbutton.setEnabled(false);
              jButton5.setEnabled(true);
            }
        } catch (SQLException ex) {
         
            Logger.getLogger(Admin_dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_votereleclistValueChanged

    private void prvotbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prvotbuttonActionPerformed
        // TODO add your handling code here:
        String elecid=votereleclist.getSelectedValue();
        if(elecid==null){
          JOptionPane.showMessageDialog(this,"No Election Selected");
        }
        else{
        if(statlabel.getText().equals("Upcoming")){
             JOptionPane.showMessageDialog(this,"The election has not yet started");
        }
        else{
            try {
                String quer1="SELECT votestat FROM voters WHERE election_id='" + elecid + "' AND userid='" + userid + "'";
                
                Statement stat=conn.createStatement();
                ResultSet rs=stat.executeQuery(quer1);
                String voted="";
                if(rs.next()){
                  voted=rs.getString(1);
                }
                if(voted.equals("y")){
                  JOptionPane.showMessageDialog(this,"You have already voted");
                }
                else{
                  String password="";
                  String quer3="SELECT otpstat FROM voters WHERE election_id='"  + elecid + "' AND userid='" + userid + "'";
                  Statement stat3=conn.createStatement();
                  ResultSet rs3=stat.executeQuery(quer3);
                  String sent="";
                  String possible="y";
                  if(rs3.next()){
                    sent=rs3.getString(1);
                  }
                  if(sent.equals("y")){
                     JOptionPane.showMessageDialog(this, "An OTP has already been sent to you");
                  }
                  else if(sent.equals("n")){
                  String quer2="SELECT email FROM users WHERE userid='" + userid + "'";
                  Statement stat2=conn.createStatement();
                  ResultSet rs2= stat.executeQuery(quer2);
                  String mailid="";
                  if(rs2.next()){
                    mailid=rs2.getString(1);
                  }
                  Random r= new Random();
                  String Capital_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
                  String Small_chars = "abcdefghijklmnopqrstuvwxyz";
                  String numbers = "0123456789";
                  String values = Capital_chars + Small_chars + numbers;
                  Random rndm_method = new Random();
                  for (int i = 0; i < 7; i++)
                 {
                    password=password+values.charAt(rndm_method.nextInt(values.length()));
                  }
                  String msg="\n\nHello User,\nUserID: " + userid + "\nElectionID: " + elecid + "\n For voting into above election, an OTP has been generated";
                  msg+="\nOTP: " + password;
                  SendEmail.send(mailid,"One Time Password Generated",msg);
                  if(SendEmail.success.equals("y")){
                    String upd="UPDATE voters SET otp='" + password + "', otpstat='y' WHERE election_id='" + elecid + "' AND userid='" + userid + "'";
                    Statement stat4=conn.createStatement();
                    stat4.executeUpdate(upd);
                    String eve=elecid+userid+"otp";
                    String quer5="SELECT CURRENT_TIMESTAMP";
                    Statement stat5=conn.createStatement();
                    ResultSet rs5=stat5.executeQuery(quer5);
                    Timestamp stts=null;
                    if(rs5.next()){
                           stts=rs5.getTimestamp(1);
                    }
                    System.out.println(stts);
                    Calendar cal= Calendar.getInstance();
                    Date d= new Date(stts.getTime());
                    cal.setTime(d);
                    cal.add(Calendar.MINUTE,2);
                    d=cal.getTime();
                    long l=d.getTime();
                    stts.setTime(l);
                    System.out.println(stts);
                     String endst="CREATE EVENT " + eve + " ON SCHEDULE AT ? DO UPDATE voters SET otpstat='n' WHERE election_id='" + elecid + "' AND userid='" + userid + "';";
        PreparedStatement ps3 = conn.prepareStatement(endst); 
        ps3.setTimestamp(1, stts);
        ps3.executeUpdate();
                  }
                  else{
                     JOptionPane.showMessageDialog(this, "Unable to send OTP\nCheck your Internet connection");
                     possible="n";
                  }
                  }
                  if(possible.equals("y")){
                    String entOTP=JOptionPane.showInputDialog(this,"An OTP has been sent to your email-id.\nPlease Enter the OTP as it will expire in 2 minutes");
                    System.out.println(entOTP);
                  quer3="SELECT otpstat FROM voters WHERE election_id='"  + elecid + "' AND userid='" + userid + "'";
                  rs3=stat.executeQuery(quer3);
                  sent="";
                  if(rs3.next()){
                    sent=rs3.getString(1);
                  }
                  if(rs.equals("n")){
                    JOptionPane.showMessageDialog(this, "The OTP sent last has already expired");
                  }
                  else{
                    String q3= "SELECT otp FROM voters WHERE election_id='" + elecid + "' AND userid='" + userid + "'";
                    Statement st3=conn.createStatement();
                    ResultSet rs4=st3.executeQuery(q3);
                    String testotp="";
                    while(rs4.next()){
                      testotp=rs4.getString(1);
                    }
                    if(testotp.equals(entOTP)){
                      new VoteFrame(userid,elecid).setVisible(true);
                      this.dispose();
                    }
                    else{
                      JOptionPane.showMessageDialog(this, "Wrong OTP");
                    }
                  }
                  }
                  }

            } catch (SQLException ex) {
                Logger.getLogger(User_dash.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_prvotbuttonActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        card.show(mainpanel,"pan6");
        DefaultListModel dlm=new DefaultListModel();
        try{
        /*dlm.addElement("name");
        dlm.addElement("age");
        dlm.addElement("address");*/
        String sql="select voters.election_id from elections inner join voters on voters.election_id=elections.electionid WHERE voters.userid='" + userid + "' and elections.election_stat='b'";
        PreparedStatement stmt=conn.prepareStatement(sql);
        ResultSet rs=stmt.executeQuery(); 
        while(rs.next())
        {
            String name=rs.getString(1);
            dlm.addElement(name);
            celeclist.setModel(dlm);
        }
        } catch(Exception e)
            {
            System.out.println("Invalid input"+e);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String eid=(String) celeclist.getSelectedValue();
            //pass=jPasswordField1.getText();
            
            PreparedStatement stmt=conn.prepareStatement(("insert into candapp values(?,?,'p',?,?)"));
           
         
            stmt.setString(1,userid);
            stmt.setString(2,eid);
            stmt.setBinaryStream(3, fin);
            stmt.setString(4,jTextArea1.getText());
             //1 specifies the first parameter in the query
            //stmt.setString(3,pass);

            int sss=stmt.executeUpdate();

            JOptionPane.showMessageDialog(this,"Thank You ");

             jTextField2.setText("");
             jTextField3.setText("");
             jTextField4.setText("");
             jTextField5.setText("");
             jLabel15.setIcon(null);
             jTextArea1.setText("");
            //txtpass.setText("");
            /*if(rs.next())
            {
                JOptionPane.showMessageDialog(rootPane,"Welcome " +name);
                new RegistrationForm().setVisible(true);

            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"Invalid User " );

            }*/
        }catch(SQLException e){
          JOptionPane.showMessageDialog(this,"You have already sent request for this election");
        
        }
        catch(Exception e)
        {
            
            System.out.println("Invalid input"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void celeclistValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_celeclistValueChanged
        // TODO add your handling code here:
        DefaultListModel dl=new DefaultListModel();
        try{
            /*dlm.addElement("name");
            dlm.addElement("age");
            dlm.addElement("address");*/
            
            String str=(String) celeclist.getSelectedValue();
            String sql=("select * from elections where electionid= '"+str+"'");
            PreparedStatement stmt=conn.prepareStatement(sql);
            ResultSet rs=stmt.executeQuery();
            String s1 =null,s2=null,s3=null,s4=null,s5=null,s6=null,s7=null;

            while(rs.next())
            {
                s1=rs.getString(1);
                s2=rs.getString(2);
                s3=rs.getString(3);
                s4=rs.getString(4);
                s5=rs.getString(5);
                s6=rs.getString(6);
                s7=rs.getString(7);
            }
            jTextField2.setText(s2);
            jTextField3.setText(s3);
            jTextField4.setText(s4);
            jTextField5.setText(s5);
        } catch(Exception e)
        {
            System.out.println("Invalid input"+e);
        }

    }//GEN-LAST:event_celeclistValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc= new JFileChooser();
        FileNameExtensionFilter filter= new FileNameExtensionFilter("*.Images","jpg","gif","png");
        FileFilter f2[]= (FileFilter[]) fc.getChoosableFileFilters();
        for(int i=0;i<f2.length;i++){
         fc.removeChoosableFileFilter(f2[i]);
        }
        fc.addChoosableFileFilter(filter);
        int result=fc.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            try {
                File selected=fc.getSelectedFile();
                String path= selected.getAbsolutePath();
                jLabel15.setIcon(ResizeImage(path));
                fin = new FileInputStream(selected);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(User_dash.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        else if(result==JFileChooser.CANCEL_OPTION){
          JOptionPane.showMessageDialog(this,"No file Selected");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel15.setIcon(null);
        fin=null;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String elecid=votereleclist.getSelectedValue();
        if(elecid==null){
          JOptionPane.showMessageDialog(this,"No Election Selected");
        }
        else{
        new CandDetails(userid,elecid,"user").setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
         int val = JOptionPane.showConfirmDialog(this,"Do you really want to delete your account?");
        System.out.println(val);
        if(val==0){
           String del1="DELETE FROM candapp WHERE userid='" + userid + "'"; 
           String del2="DELETE FROM elecvotes WHERE cand_id='" + userid + "'";
           String del3="DELETE FROM voters WHERE userid='" + userid + "'";
           String del4="DELETE FROM users WHERE userid='" + userid + "'";
            try {
                Statement stat=conn.createStatement();
                stat.executeUpdate(del1);
                 stat.executeUpdate(del2);
                  stat.executeUpdate(del3);
                   stat.executeUpdate(del4);
                new homescr().setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Org_dash.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String eid=votereleclist.getSelectedValue();
        
        if(eid==null){
            JOptionPane.showMessageDialog(this,"No Election Selected");
            return;
          }
        
        new ResultFrame(eid,"Completed").setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    public ImageIcon ResizeImage(String ImagePath){
      ImageIcon myImage= new ImageIcon(ImagePath);
      Image img=myImage.getImage();
      Image newimg= img.getScaledInstance(jLabel15.getWidth(), jLabel15.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon image=new ImageIcon(newimg);
      return image;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList celeclist;
    private javax.swing.JLabel durlabel;
    private javax.swing.JTable electab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTable orgtab;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel pan3;
    private javax.swing.JPanel pan4;
    private javax.swing.JPanel pan5;
    private javax.swing.JPanel pan6;
    private javax.swing.JButton prvotbutton;
    private javax.swing.JLabel statlabel;
    private javax.swing.JLabel stlabel;
    private javax.swing.JTable usertab;
    private javax.swing.JList<String> votereleclist;
    // End of variables declaration//GEN-END:variables
}
