package ProjFrames;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BoxLayout;
import javax.swing.JOptionPane;

import Services.DBconn;
import Services.SendEmail;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class UserReg extends javax.swing.JFrame {

    /**
     * Creates new form UserReg
     */
    Connection conn;
    String user;
    public UserReg(String str) {
        initComponents();
          try {
                conn= (new DBconn()).getDBconnection();
                user=str;
            } catch (Exception ex) {
                System.out.println("Connecting  problem");
                Logger.getLogger(Loginscr.class.getName()).log(Level.SEVERE, null, ex);
            }
          if(!user.equals("user")){
             jButton1.setEnabled(false);
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mailtf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mobtf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usertf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        passtf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        groupcb = new javax.swing.JComboBox<>();
        Regb = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        getContentPane().setLayout(new BoxLayout(getContentPane(),BoxLayout.Y_AXIS));

        javax.swing.JPanel pnl = new javax.swing.JPanel();
        pnl.setPreferredSize(new Dimension(800,75));
        getContentPane().add(pnl);
        
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Registration");
        getContentPane().add(jLabel1);
        
        jPanel1.setLayout(new GridLayout(3,1));
        
        javax.swing.JPanel jPanel11 = new javax.swing.JPanel();
        jPanel11.setLayout(new FlowLayout());
        javax.swing.JPanel jPanel12 = new javax.swing.JPanel();
        jPanel12.setLayout(new FlowLayout());
        javax.swing.JPanel jPanel13 = new javax.swing.JPanel();
        jPanel13.setLayout(new FlowLayout());

        Nametf.setPreferredSize(new Dimension(112,28));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name:");
        jPanel11.add(jLabel2);
        jPanel11.add(Nametf);
        jPanel1.add(jPanel11);

        Nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NametfActionPerformed(evt);
            }
        });

        mailtf.setPreferredSize(new Dimension(112,28));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("E-mail:");
        jPanel12.add(jLabel3);
        jPanel12.add(mailtf);
        jPanel1.add(jPanel12);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mobile No.:");
        jPanel13.add(jLabel4);
        mobtf.setPreferredSize(new Dimension(112,28));
        jPanel13.add(mobtf);
        jPanel1.add(jPanel13);
        
        getContentPane().add(jPanel1);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1);
        
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel21 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel22 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel23 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel24 = new javax.swing.JPanel();
        
        jPanel2.setLayout(new GridLayout(4,1));
        jPanel21.setLayout(new FlowLayout());
        jPanel22.setLayout(new FlowLayout());
        jPanel23.setLayout(new FlowLayout());
        jPanel24.setLayout(new FlowLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Set your User-ID and password");
        getContentPane().add(jLabel6);

        
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("User-ID:");
        jPanel21.add(jLabel7);

        usertf.setPreferredSize(new Dimension(112,28));
        usertf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertfActionPerformed(evt);
            }
        });
        jPanel21.add(usertf);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Password:");
        jPanel22.add(jLabel8);
        passtf.setPreferredSize(new Dimension(112,28));
        jPanel22.add(passtf);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Branch:");
        jPanel23.add(jLabel9);

        groupcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer", "Mechanical", "Electrical", "Electronics", "IT", "IC", "Chemical", "Civil", "Other group" }));
        jPanel23.add(groupcb);

        Regb.setText("Register");
        Regb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegbActionPerformed(evt);
            }
        });
        jPanel24.add(Regb);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel24.add(jButton1);
        
        jPanel2.add(jPanel21);
        jPanel2.add(jPanel22);
        jPanel2.add(jPanel23);
        jPanel2.add(jPanel24);
        getContentPane().add(jPanel2);
        
        getContentPane().add(new javax.swing.JPanel());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NametfActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_NametfActionPerformed

    private void usertfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertfActionPerformed

    private void RegbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegbActionPerformed
                                             
            // TODO add your handling code here:
            String name=Nametf.getText();
            String mail=mailtf.getText();
            String mob=mobtf.getText();
            char[] c=mob.toCharArray();
            String grid=(String) groupcb.getSelectedItem();
            String usid=usertf.getText();
            String passw=passtf.getText();
            System.out.println(name + mail + mob + usid + passw);
            String quer1= "SELECT * FROM users";
            Statement stat2;
        try {
            stat2 = conn.createStatement();
            ResultSet rs2=stat2.executeQuery(quer1);
            while(rs2.next()){
              if(rs2.getString(1).equals(usid)){
                JOptionPane.showMessageDialog(this,"This username already exists.\nPlease enter other username");
                return;
              }
            }
        } catch (SQLException ex) {
            Logger.getLogger(UserReg.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            if(name.equals("") || mail.equals("") || mob.equals("") || usid.equals("") || passw.equals("")){
                
                JOptionPane.showMessageDialog(this,"One or more field may be empty");
                return;
            }
            
            try{
                if(c.length!=10)
                    throw new Exception();
                for(int i=0;i<10;i++){
                    if(!Character.isDigit(c[i])){
                        throw new Exception();
                    }
                }
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Entered Mobile Number is not valid");
                mobtf.selectAll();
                return;
            }
            String str="";
            if(user.equals("user")){
                  String Capital_chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
                  String Small_chars = "abcdefghijklmnopqrstuvwxyz";
                  String numbers = "0123456789";
                  String values = Capital_chars + Small_chars + numbers;
                  Random rndm_method = new Random();
                  String password="";
                  for (int i = 0; i < 7; i++)
                 {
                    password=password+values.charAt(rndm_method.nextInt(values.length()));
                  }
                  String msg="\n\nHello User,\nUserID: " + usid + "\n.For checking your email, an OTP has been generated";
                  msg+="\nOTP: " + password;
                  SendEmail.send(mail,"One Time Password Generated",msg);
                  if(SendEmail.success.equals("y")){
                      String enter=JOptionPane.showInputDialog(this, "An OTP has been sent to your mail.\n Please enter it.");
                     if(enter.equals(password)){
                         str="INSERT INTO userapp VALUES(\"" + usid + "\", \"" + passw + "\", \"" + name + "\", \"" + mail + "\", \"" + mob + "\", \"" + grid + "\", 'p')";
                      }
                     else{
                        JOptionPane.showMessageDialog(this,"Wrong OTP-OTP test failed. You can repeat the procedure");
                        return;
                     }
                  }
                  else{
                      JOptionPane.showMessageDialog(this,"Unable to send OTP\nCheck your Internet connection.");
                      return;
                  }
            }
            else if(user.equals("admin"))
              str="INSERT into users VALUES(\"" + usid + "\", \"" + passw + "\", \"" + name + "\", \"" + mail + "\", \"" + grid + "\", \"" + mob + "\")";  
         try{   
            Statement stat=conn.createStatement();
            stat.executeUpdate(str);
            if(user.equals("user"))
                JOptionPane.showMessageDialog(this,"Request for approval has been sent");
            else
                JOptionPane.showMessageDialog(this,"Registration done successfully!!!");
            new UserReg(user).setVisible(true);
            this.dispose();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"This username already exists.\nPlease enter other username");
            Logger.getLogger(UserReg.class.getName()).log(Level.SEVERE, null,ex);
        }
        
    }//GEN-LAST:event_RegbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Regscr().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nametf;
    private javax.swing.JButton Regb;
    private javax.swing.JComboBox<String> groupcb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mailtf;
    private javax.swing.JTextField mobtf;
    private javax.swing.JTextField passtf;
    private javax.swing.JTextField usertf;
    // End of variables declaration//GEN-END:variables
}
